feat: publish all packages + select tag (#11)

diff --git a/.github/workflows/publish_package_to_npmjs.yaml b/.github/workflows/publish_package_to_npmjs.yaml
--- a/.github/workflows/publish_package_to_npmjs.yaml
+++ b/.github/workflows/publish_package_to_npmjs.yaml
@@ -4,30 +4,84 @@ on:
   workflow_dispatch:
     inputs:
       package_name:
-        description: Package name
+        description: Select the package to publish or choose "all" to publish all specified packages
         type: choice
         required: true
         options:
+          - all
           - theme-pack
           - scaffold
           - csk-cli
+      publish_env:
+        description: Select the environment to publish to (production or alpha)
+        type: choice
+        required: true
+        options:
+          - production
+          - alpha
+
 jobs:
   publish_package:
     runs-on: ubuntu-latest
     permissions:
       contents: read
       id-token: write
+
+    env:
+      PACKAGES: "theme-pack scaffold csk-cli" # Define packages as a single string variable
+
     steps:
-      - uses: actions/checkout@v4
-      # Setup .npmrc file to publish to npm
-      - uses: actions/setup-node@v4
+      # Step 1: Checkout repository
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      # Step 2: Setup Node.js environment
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
         with:
-          node-version: '20.x'
-          registry-url: 'https://registry.npmjs.org'
-      - run: npm ci
-      - run: |
-          cd ./packages/${{ inputs.package_name }}
-          npm run build
-          npm publish
+          node-version: "20.x"
+          registry-url: "https://registry.npmjs.org"
+
+      # Step 3: Install dependencies
+      - name: Install dependencies
+        run: npm ci
+
+      # Step 4: Publish Selected Package(s)
+      - name: Publish Package(s)
+        run: |
+          if [ "${{ inputs.publish_env }}" == "alpha" ]; then
+            PUBLISH_TAG="--tag alpha"
+          else
+            PUBLISH_TAG=""
+          fi
+
+          if [ "${{ inputs.package_name }}" == "all" ]; then
+            echo "Publishing package(s): ${{ inputs.package_name }}"
+            IFS=' ' read -r -a package_array <<< "$PACKAGES"
+            for i in "${!package_array[@]}"; do
+              pkg=${package_array[$i]}
+              echo "Publishing package: $pkg to ${{ inputs.publish_env }} environment"
+              cd ./packages/$pkg
+              npm run build
+              npm publish $PUBLISH_TAG
+              if [ $? -eq 0 ]; then
+                if [ $i -lt $((${#package_array[@]} - 1)) ]; then
+                  echo "Successfully published $pkg. Waiting for 20 seconds before publishing the next package..."
+                  sleep 20
+                else
+                  echo "Successfully published the last package: $pkg."
+                fi
+              else
+                echo "Failed to publish $pkg. Exiting..."
+                exit 1
+              fi
+              cd -
+            done
+          else
+            echo "Publishing selected package: ${{ inputs.package_name }} to ${{ inputs.publish_env }} environment"
+            cd ./packages/${{ inputs.package_name }}
+            npm run build
+            npm publish $PUBLISH_TAG
+          fi
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
